# Generated by Django 6.1.1 on 2026-09-15 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 15, 5, 52, 21, 411811, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
